services:
  - type: web
    name: citasalud
    env: docker
    plan: free
    branch: rama2
    dockerfilePath: .devcontainer/Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: CONTEXT_PATH
        value: /api
      - key: DB_URL
        value: jdbc:postgresql://dpg-d170edmmcj7s73cll220-a:5432/bd_citassalud
      - key: DB_USERNAME
        value: bd_citassalud_a24i_user
      - key: DB_PASSWORD
        value: 9avCX5rbXW8AgIpJy1gZ7mkX3lj8AZzy
      - key: SWAGGER_SERVER_URL
        value: https://citasalud.onrender.com/api
      - key: JWT_SECRET
        value: citasalud2025clavesupersecretajwttokenaudmuchoscaracteres2025
      - key: JWT_EXPIRATION
        value: 86400000