version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bd_citassalud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1

  redis:
    image: redis
    restart: unless-stopped

volumes:
  postgres-data: